[windows.packages.scoop]
enable = true
type = "custom"
[windows.packages.scoop.options]
buckets = [
  { id = "extras"                 , url = "extras"                                    },
  { id = "nerd-fonts"             , url = "nerd-fonts"                                },
  { id = "tlipoca9_scoop-buckets" , url = "https://github.com/tlipoca9/scoop-bucket"  },
]

[windows.packages."main/git"]
enable = true
type = "scoop"
checker = { type = "command", command = "git" }

[windows.packages."main/innounp"]
enable = true
type = "scoop"
checker = { type = "command", command = "innounp" }

[windows.packages."main/sudo"]
enable = true
type = "scoop"
checker = { type = "command", command = "sudo" }

[windows.packages."main/7zip"]
enable = true
type = "scoop"
checker = { type = "command", command = "7z" }

[windows.packages."main/dark"]
enable = true
type = "scoop"
checker = { type = "command", command = "dark" }

[windows.packages."main/curl"]
enable = true
type = "scoop"
checker = { type = "command", command = "curl" }

[windows.packages."main/nu"]
enable = true
type = "scoop"
checker = { type = "command", command = "nu" }

[windows.packages."main/mise"]
enable = true
type = "scoop"
checker = { type = "command", command = "mise" }

[windows.packages."main/atuin"]
enable = true
type = "scoop"
checker = { type = "command", command = "atuin" }

[windows.packages."main/make"]
enable = true
type = "scoop"
checker = { type = "command", command = "make" }

[windows.packages."main/mingw"]
enable = true
type = "scoop"
checker = { type = "command", command = "gcc" }


[windows.packages."extras/wezterm"]
enable = true
type = "scoop"
checker = { type = "command", command = "wezterm" }

[windows.packages."nerd-fonts/FiraCode-NF"]
enable = true
type = "scoop"
checker = { type = "font", font = "FiraCode Nerd Font Mono" }


