[linux.packages.homebrew]
enable = true
type = "script"
checker = { type = "command", command = "brew" }
installer = """
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
"""
post_install = """
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
"""

[linux.packages.gcc]
enable = true
type = "homebrew"
checker = { type = "command", command = "gcc" }
installer = { type = "formula" }

[linux.packages.nushell]
enable = true
type = "homebrew"
checker = { type = "command", command = "nu" }
installer = { type = "formula" }

[linux.packages.git]
enable = true
type = "homebrew"
checker = { type = "command", command = "git" }
installer = { type = "formula" }

[linux.packages.curl]
enable = true
type = "homebrew"
checker = { type = "command", command = "curl" }
installer = { type = "formula" }

[linux.packages.mise]
enable = true
type = "homebrew"
checker = { type = "command", command = "mise" }
installer = { type = "formula" }

[linux.packages.atuin]
enable = true
type = "homebrew"
checker = { type = "command", command = "atuin" }
installer = { type = "formula" }

[linux.packages.file]
enable = true
type = "homebrew"
checker = { type = "command", command = "file" }
installer = { type = "formula" }

[linux.packages.kcat]
enable = true
type = "homebrew"
checker = { type = "command", command = "kcat" }
installer = { type = "formula" }


